/******************************************************************************
*
* project name:   FAT-Engine
* file name:      fatd1.c
* initial date:   25/02/2001
* author:         thomas.nussbaumer@gmx.net
*
* description:    FAT-Engine - Demo 1 (Time Demo)
*
* $Id: fatd1.c,v 1.16 2002/05/08 15:35:13 tnussb Exp $
*
******************************************************************************/

#define USE_TI89
#define USE_TI92P
#define USE_V200
#include "../includes/fat.h"


#define  MAP_WIDTH        16
#define  MAP_HEIGHT       16

//-------------------------------------------------------------------
// defines the used map: 0 = no wall, 1 = texture1, 2 = texture2 etc.
// NOTE: the array tex64 which gets handed over to the engine as
//       part of the FATCONFIG structure has to as much textures as
//       you have specified in this map.
//       For example: if the highest number in the map is 3 then
//       tex64 has to hold 3 textures (64x64 pixels with 2 planes)
//-------------------------------------------------------------------

char map[MAP_WIDTH*MAP_HEIGHT] = {
     2, 1,   2, 2,   1, 2, 2, 2, 2, 2,   2,   1, 2,   2, 1, 2,
     2, 0,   0, 0,   0, 0, 0, 0, 0, 0,   0,   0, 0,   0, 0, 1,
     2, 0,   2, 2, 127, 2, 2, 0, 0, 2,   2,   2, 2,   2, 0, 2,
     2, 0,   2, 0,   0, 0, 2, 0, 0, 2,   0,   0, 0,   1, 0, 2,
     2, 0, 127, 0,   0, 0, 0, 0, 0, 0,   0,   0, 0,   2, 0, 2,
     2, 0,   2, 0,   0, 0, 2, 0, 0, 2,   0,   0, 0,   1, 0, 2,
     2, 0,   0, 2,   2, 2, 0, 0, 0, 0,   2,   2, 2,   0, 0, 2,
     2, 0,   0, 0,   0, 0, 0, 0, 0, 0,   0,   0, 0,   0, 0, 2,
     2, 0,   2, 2,   2, 2, 2, 0, 0, 2, 127,   1, 2,   2, 0, 2,
     2, 0,   1, 0,   0, 0, 2, 0, 0, 2,   0,   0, 0,   1, 0, 2,
     2, 0,   2, 0,   0, 0, 0, 0, 0, 0,   0,   0, 0,   2, 0, 2,
     2, 0, 127, 0,   0, 0, 0, 0, 0, 0,   0,   0, 0, 127, 0, 2,
     2, 0,   1, 0,   0, 0, 2, 0, 0, 2,   0,   0, 0,   1, 0, 2,
     2, 0,   2, 2,   2, 2, 2, 0, 0, 2,   2, 127, 2,   2, 0, 2,
     2, 0,   0, 0,   0, 0, 0, 0, 0, 0,   0,   0, 0,   0, 0, 1,
     2, 1,   2, 2,   1, 2, 2, 2, 2, 2,   2,   1, 2,   2, 1, 2
};


//-----------------------------------------------------------------------------
// include the utility routines ...
//-----------------------------------------------------------------------------
#include "utils.c"

//-----------------------------------------------------------------------------
// include file containing the texture and genericdata indices into fatdtx
// (automatically generated by TexMaker)
//-----------------------------------------------------------------------------
#include "indices.h"


short display_offsetx = 0; // will be set depending on calctype (TI89 or TI92p)
short display_offsety = 0; // will be set depending on calctype (TI89 or TI92p)

typedef struct {
    short xpos;
    short ypos;
    short orientation;
}
BENCHMARK_VIEW;

static const BENCHMARK_VIEW benchmark_views[] = {
    {96,  96,  ANGLE_EAST},
    {480, 480, ANGLE_SOUTH},
    {288, 672, ANGLE_WEST},
    {864, 928, ANGLE_NORTH}
};

typedef struct {
    unsigned long start_int5;
    unsigned long start_frame;
    unsigned long min_fpm;
    unsigned long max_fpm;
    unsigned long current_fpm;
    unsigned long samples;
}
BENCHMARK_STATS;

void ResetBenchmarkStats(BENCHMARK_STATS* stats, unsigned long frame) {
    stats->start_int5  = int5_counter;
    stats->start_frame = frame;
    stats->min_fpm     = 0xFFFFFFFF;
    stats->max_fpm     = 0;
    stats->current_fpm = 0;
    stats->samples     = 0;
}

unsigned long GetAverageBenchmarkFPM(BENCHMARK_STATS* stats) {
    unsigned long elapsed = int5_counter - stats->start_int5;
    unsigned long frames  = stats->current_fpm; // reuse as temp
    if (!elapsed) return 0;
    frames = (stats->samples) ?
        /* use total elapsed */ ((stats->start_frame + stats->samples) - stats->start_frame) : 0;
    // Not ideal — just use the running calculation
    return stats->current_fpm;
}

short UpdateBenchmarkStats(BENCHMARK_STATS* stats, unsigned long frame_counter) {
    unsigned long elapsed = int5_counter - stats->start_int5;
    if (elapsed >= 20) {
        unsigned long frames = frame_counter - stats->start_frame;
        unsigned long fpm = frames * 1200 / elapsed;
        stats->current_fpm = fpm;
        stats->start_int5  = int5_counter;
        stats->start_frame = frame_counter;
        stats->samples++;
        if (fpm < stats->min_fpm) stats->min_fpm = fpm;
        if (fpm > stats->max_fpm) stats->max_fpm = fpm;
        return 1;
    }
    return 0;
}

void SetCounterValue(COUNTER* counter, unsigned long value) {
    short i;
    for (i = counter->length - 1; i >= 0; i--) {
        counter->newcount[i] = value % 10;
        value /= 10;
    }
}

//=============================================================================
// initializes GUI (darkgray background, tiny logo and counter)
//=============================================================================
void InitGUI(COUNTER *counter) {
    static unsigned long empty[] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};

    memset(GetPlane(LIGHT_PLANE),0,LCD_SIZE);
    memset(GetPlane(DARK_PLANE),0xff,LCD_SIZE);

    Sprite32(158-32+display_offsetx,display_offsety+2,16,empty,GetPlane(0),SPRT_AND);
    Sprite32(158-32+display_offsetx,display_offsety+2,16,FAT_GetTinyLogo(),GetPlane(0),SPRT_OR);
    Sprite32(158-32+display_offsetx,display_offsety+2,16,empty,GetPlane(1),SPRT_AND);
    Sprite32(158-32+display_offsetx,display_offsety+2,16,FAT_GetTinyLogo()+16,GetPlane(1),SPRT_OR);

    InitCounter(counter,158-6*5+display_offsetx,99-10+display_offsety,5,0);
    DrawCounter(counter);
}


//=============================================================================
// cycles through a few representative viewpoints for repeatable benchmarking
//=============================================================================
void UpdateBenchmarkCamera(FATCONFIG* fc) {
    unsigned short view_idx = (unsigned short)((fc->frame_counter >> 8) & 3);
    unsigned short sweep    = (unsigned short)(fc->frame_counter & 0xff);
    short          offset   = (short)(((unsigned long)sweep * ANGLE_360) >> 8);

    fc->cam_xpos        = benchmark_views[view_idx].xpos;
    fc->cam_ypos        = benchmark_views[view_idx].ypos;
    fc->cam_orientation = FAT_ClampAngle(benchmark_views[view_idx].orientation + offset);
}


//=============================================================================
// shows min/avg/max FPM summary for the last benchmark run
//=============================================================================
void ShowBenchmarkSummary(BENCHMARK_STATS* stats) {
    char buffer[40];

    sprintf(buffer,"BENCH %lu/%lu/%lu",
            stats->min_fpm,
            GetAverageBenchmarkFPM(stats),
            stats->max_fpm);
    ST_helpMsg(buffer);
}


//=============================================================================
// display live FPM (frames per minute) using int5_counter (~20Hz) as timebase
//=============================================================================
void frame_drawn(FATCONFIG* fc,COUNTER* counter,BENCHMARK_STATS* stats) {
    if (UpdateBenchmarkStats(stats,fc->frame_counter)) {
        SetCounterValue(counter,stats->current_fpm);
        DrawCounter(counter);
    }
}


//=============================================================================
// add all doors defined in map
//=============================================================================
void CreateDoors(TEXCONFIG* tex_door, TEXCONFIG* tex_side) {
    short x, y;
    for (y=1; y<(MAP_HEIGHT-1); ++y) {
        for (x=1; x<(MAP_WIDTH-1); ++x) {
            if (map[y*MAP_WIDTH+x] == 127) {
                if (map[y*MAP_WIDTH+(x-1)]>0 && map[y*MAP_WIDTH+(x+1)]>0) {
                    FAT_AddDoor(x, y, DOOR_HORIZONTAL, DOOR_CLOSED, 0, tex_door, tex_side, NULL);
                }
                else {
                    FAT_AddDoor(x, y, DOOR_VERTICAL, DOOR_CLOSED, 0, tex_door, tex_side, NULL);
                }
            }
        }
    }
}


//=============================================================================
// animates a door one step; clears anim_x to -1 when done
//=============================================================================
void AnimateDoor(FATCONFIG* fc, short* anim_x, short* anim_y, short opening) {
    FATDOOR* door;
    if (*anim_x < 0) return;

    door = FAT_GetDoor(*anim_x, *anim_y);
    if (!door) { *anim_x = -1; return; }

    if (opening) {
        door->position += 2;
        if (door->position >= 64) {
            door->position = 64;
            door->state = DOOR_OPEN;
            *(fc->map_data + fc->map_width * (*anim_y) + *anim_x) = -127;
            *anim_x = -1;
        } else {
            door->state = DOOR_OPENING;
        }
    } else {
        door->position -= 2;
        // Block passage immediately when closing starts (engine needs 127 to render door)
        *(fc->map_data + fc->map_width * (*anim_y) + *anim_x) = 127;
        if (door->position <= 0) {
            door->position = 0;
            door->state = DOOR_CLOSED;
            *anim_x = -1;
        } else {
            door->state = DOOR_CLOSING;
        }
    }
}


//=============================================================================
// minimap overlay: 64x64 pixel map (4x scale) in the GUI area right of viewport
// Uses same approach as Number_XOR_DarkPlane: GetPlane(DARK_PLANE) + only dark plane
// Row stride is always 15 shorts (240px/30 bytes per row, even on TI-89)
//=============================================================================
void DrawMinimap(FATCONFIG* fc) {
    unsigned short* dark;
    short row, col, py, tx, ty, ofs;
    short base_y, base_short;
    unsigned short mask;
    short sx;

    dark = (unsigned short*)GetPlane(DARK_PLANE);

    if (TI89) {
        base_y     = 25;
        base_short = 6;    // x=96
    } else {
        base_y     = 38;
        base_short = 9;    // x=144
    }

    // Each tile = 4x4 pixels. 16 tiles * 4px = 64px wide (4 shorts)
    // Background is dark gray: light=0, dark=1
    // Walls = white: dark=0.  Corridors = dark gray: dark=1
    // Write inverted wall mask to dark plane only (light plane stays 0 from InitGUI)
    for (row = 0; row < 16; row++) {
        unsigned short words[4];
        char* mr = map + row * MAP_WIDTH;
        words[0] = words[1] = words[2] = words[3] = 0;

        for (col = 0; col < 16; col++) {
            if (mr[col] > 0) {
                words[col >> 2] |= (unsigned short)0xF000 >> ((col & 3) * 4);
            }
        }

        for (py = 0; py < 4; py++) {
            ofs = (base_y + row * 4 + py) * 15 + base_short;
            dark[ofs]     = ~words[0];
            dark[ofs + 1] = ~words[1];
            dark[ofs + 2] = ~words[2];
            dark[ofs + 3] = ~words[3];
        }
    }

    // Player dot — 4x4 blinking block (XOR dark plane only, like counter digits)
    tx = fc->cam_xpos >> 6;
    ty = fc->cam_ypos >> 6;
    if (tx >= 0 && tx < 16 && ty >= 0 && ty < 16) {
        if ((fc->frame_counter & 8) < 4) {
            mask = (unsigned short)0xF000 >> ((tx & 3) * 4);
            sx = base_short + (tx >> 2);
            for (py = 0; py < 4; py++) {
                ofs = (base_y + ty * 4 + py) * 15 + sx;
                dark[ofs] ^= mask;
            }
        }
    }
}


//=============================================================================
// as usual ... our main function
//=============================================================================
void _main(void) {
    PADSTATES       key    = 0;
    unsigned char*  bg_img = NULL;
    short           i,j;
    unsigned short* dest;
    TEXCONFIG       textures[4];
    LCD_BUFFER      lcd;
    HANDLE          texfile = 0;
    unsigned char*  src     = 0;
    short           result;
    COUNTER         frames_display;
    BENCHMARK_STATS benchmark_stats;
    short           benchmark_mode        = 0;
    short           benchmark_toggle_down = 0;
    short           door_anim_x           = -1;
    short           door_anim_y           = -1;
    short           door_anim_opening     = 0;

    FATCONFIG fc = {
        MAP_WIDTH,  // width of map
        MAP_HEIGHT, // height of map
        map,        // pointer to map data
        textures,   // pointer to textures array
        0,          // number of sprites
        NULL,       // the sprite array
        96,         // start pos_x
        96,         // start pos_y
        ANGLE_EAST, // orientation
        NULL,       // destination plane0
        NULL,       // destination plane1
        NULL,       // background image
        0           // frame counter
    };

    //-------------------------------------------------------------------------
    // before we try to do anything else we have to initialize the engine
    // its only valid to proceed if FAT_LOADOKAY gets returned
    //-------------------------------------------------------------------------
    if ((result = FAT_LoadEngine()) != FAT_LOADOKAY) {
        switch(result) {
            case FAT_NOTGHOSTSPACE: ST_helpMsg("ERROR: client no exepacked!");break;
            case FAT_NOTFOUND:      ST_helpMsg("ERROR: no matching engine found");break;
            case FAT_LOCKFAILED:    ST_helpMsg("ERROR: locking engine failed");break;
            case FAT_OUTOFMEM:      ST_helpMsg("ERROR: out of memory");break;
            default:                ST_helpMsg("ERROR: unknown errorcode");break;
        }
        return;
    }

    //-------------------------------------------------------------------------
    // try to load the used textures from fatdtx ...
    //-------------------------------------------------------------------------
    if ((texfile = FAT_GetHandleOfFile("fatdtx"))) {
        if ((src = FAT_LockHandleOfFile(texfile))) {
            // load house wall textures
            if (!FAT_LoadTextures(textures,src+2,TEXIDX_HOUSE1,2)) {
                src = 0; // just to indicate something went wrong
            }
            // load door textures
            if (!FAT_LoadTextures(&textures[2],src+2,TEXIDX_DEMO3WALL,2)) {
                src = 0;
            }
        }
    }

    //-------------------------------------------------------------------------
    // check if loading failed ...
    //-------------------------------------------------------------------------
    if (!texfile || !src) {
        FAT_UnloadEngine();
        if (texfile) FAT_UnlockHandleOfFile(texfile);
        ST_helpMsg("ERROR: cannot textures from fatdtx");
        return;
    }

    CreateDoors(&textures[3], &textures[2]);

    LCD_save(lcd);


    //-------------------------------------------------------------------------
    // allocate space for a background image and fill the lower part of the
    // light plane with 0xff to simulate a floor ...
    //-------------------------------------------------------------------------
    if (!(bg_img = (unsigned char*)malloc(1152*2))) {
        FAT_UnloadEngine();
        FAT_UnlockHandleOfFile(texfile);
        ST_helpMsg("ERROR: out of mem");
        return;
    }
    memset(bg_img,0x00,1152*2);

    dest = (unsigned short*)bg_img;
    for (i=0;i<6;i++) {
        for (j=0;j<48;j++) *dest++ = 0x0000;
        for (j=0;j<48;j++) *dest++ = 0xffff;
    }
    fc.background = (unsigned short*)bg_img;

    InstallDummyHandlerForINTs();
    ResetBenchmarkStats(&benchmark_stats,fc.frame_counter);

    //-------------------------------------------------------------------------
    // initialize grayscales, clear both planes and set the destination plane
    // addresses for the FAT-Engine
    //-------------------------------------------------------------------------
    if (!GrayOn()) {
        free(bg_img);
        RestoreHandlerForINTs();
        FAT_UnloadEngine();
        FAT_UnlockHandleOfFile(texfile);
        ST_helpMsg("ERROR: out of mem");
        return;
    }

    //-------------------------------------------------------------------------
    // display the FAT-Engine's splashscreen
    //-------------------------------------------------------------------------
    FAT_DisplayLogo(100);

    fc.dest_plane0 = GetPlane(0)+30*2;  // center vertically
    fc.dest_plane1 = GetPlane(1)+30*2;  // center vertically

    //-------------------------------------------------------------------------
    // setup calculator type specials
    //-------------------------------------------------------------------------
    if (TI89) {
        display_offsetx = 0;
        display_offsety = 0;
    }
    else {
        // TI92p or V200
        display_offsetx  = 40;
        display_offsety  = 14;
        fc.dest_plane0  += (14*30+4)/2;
        fc.dest_plane1  += (14*30+4)/2;
    }

    //-------------------------------------------------------------------------
    // initialize the GUI
    //-------------------------------------------------------------------------
    InitGUI(&frames_display);


    //-------------------------------------------------------------------------
    // the main rendering loop ...
    //-------------------------------------------------------------------------
    do {
        if (benchmark_mode) UpdateBenchmarkCamera(&fc);

        FAT_Render(&fc);   // render image
        AnimateDoor(&fc, &door_anim_x, &door_anim_y, door_anim_opening);
        DrawMinimap(&fc);

        frame_drawn(&fc,&frames_display,&benchmark_stats);  // handles frame counter drawing

        key = FAT_GetPadState();
        if (key & PADSTATE_KB) {
            if (!benchmark_toggle_down) {
                benchmark_toggle_down = 1;
                if (!benchmark_mode) {
                    benchmark_mode = 1;
                    ResetBenchmarkStats(&benchmark_stats,fc.frame_counter);
                    ST_helpMsg("BENCHMARK ON");
                }
                else {
                    ShowBenchmarkSummary(&benchmark_stats);
                    benchmark_mode = 0;
                    ResetBenchmarkStats(&benchmark_stats,fc.frame_counter);
                }
            }
        }
        else {
            benchmark_toggle_down = 0;
        }

        if (key) {
            if (key & PADSTATE_ESC)    break;
            if (benchmark_mode)        continue;
            if (key & PADSTATE_UPDOWN) PlayerMove(&fc,key & PADSTATE_UP,0);
            if (key & PADSTATE_LEFTRIGHT) {
                // STRAFE KEY: 2ND (TI-89) / F1 (TI-92p)
                if (key & PADSTATE_KA) {
                    PlayerMove(&fc,key&PADSTATE_RIGHT,1);
                }
                else {
                    PlayerTurn(&fc,key&PADSTATE_RIGHT,ANGLE_015/2);
                }
            }
            if ((key & PADSTATE_PLUS || key & PADSTATE_MINUS) && door_anim_x < 0) {
                short dtx = ((FAT_Cos16384(fc.cam_orientation) >> 8)+fc.cam_xpos)>>6;
                short dty = ((FAT_Sin16384(fc.cam_orientation) >> 8)+fc.cam_ypos)>>6;
                if (FAT_GetDoor(dtx,dty)) {
                    door_anim_x = dtx;
                    door_anim_y = dty;
                    door_anim_opening = (key & PADSTATE_PLUS) ? 1 : 0;
                }
            }
        }
    }
    while(1);

    //-------------------------------------------------------------------------
    // some clean stuff ...
    //-------------------------------------------------------------------------
    FAT_AllKeysReleased();
    GrayOff();
    free(bg_img);
    LCD_restore(lcd);
    if (benchmark_stats.samples) ShowBenchmarkSummary(&benchmark_stats);
    else                         ST_helpMsg(FAT_GetPoweredByString());
    FAT_UnlockHandleOfFile(texfile);  // unlock texture file
    FAT_UnloadEngine();
    RestoreHandlerForINTs();
    OSqclear(kbd_queue());
}

//#############################################################################
// Revision History
//#############################################################################
//
// $Log: fatd1.c,v $
// Revision 1.16  2002/05/08 15:35:13  tnussb
// (1) display of FAT splashscreen (FAT_DisplayLogo) added
// (2) GUI of demos completely revised
//
// Revision 1.15  2002/05/07 15:22:12  tnussb
// stupid double call of FAT_LoadEngine() fixed
//
// Revision 1.14  2002/04/30 17:41:44  tnussb
// using now defines from automatically generated headerfile indices.h for indices into
// our texture file
//
// Revision 1.13  2002/04/26 13:10:49  tnussb
// if FAT_LoadEngine() fails different strings will be displayed yet
//
// Revision 1.12  2002/04/25 19:26:38  tnussb
// generic commit for engine version v1.05
//
// Revision 1.11  2002/04/24 17:41:54  tnussb
// (1) using now FAT_GetPadState() to query key presses
// (2) movement evaluation block rewritten (handles now strafing, too)
//
// Revision 1.10  2002/04/18 12:14:47  tnussb
// using now fatdtx texture file instead of embedded textures
//
// Revision 1.9  2002/04/16 11:36:37  tnussb
// All calls to GrayMode() replaced by GrayOn/GrayOff calls
//
// Revision 1.8  2002/04/08 20:18:16  tnussb
// using now signed char (instead of unsigned char) for map
//
// Revision 1.7  2002/03/26 11:56:24  tnussb
// all warnings reported by -Wall fixed
//
// Revision 1.6  2002/03/11 09:17:40  tnussb
// USE_V200 added
//
// Revision 1.5  2002/03/07 11:13:51  tnussb
// restores now previously set font at the end
//
// Revision 1.4  2002/03/06 12:32:12  tnussb
// (1) OutputTitle completely rewritten (uses now new exported "functions" of FAT-Engine)
// (2) InstallDummyHandleForINT1(), RestoreHandlerForINT1() renamed, because AUTO_INT5 will be redirected now, too
// (3) don't use SAVE_SCREEN anymore, but use own screenbackup to enable writting to the statusline
//
// Revision 1.3  2002/03/01 11:09:55  tnussb
// generic commit for sourcecode release v0.81
//
// Revision 1.2  2001/03/11 19:16:24  Thomas Nussbaumer
// using now _rowread() and smaller delta values
//
// Revision 1.1  2001/03/04 20:13:38  Thomas Nussbaumer
// initial version
//
//
